@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVjNWRlZGRiNTFkZjZhNTc5YzUxY2Q0NCIsInVzZXJuYW1lIjoiRHJhY29jdGl4IiwiYWRtaW4iOmZhbHNlLCJleHAiOjE1NDk2NTk2MjEwMjYsImlhdCI6MTU0OTY1OTYxMX0.qHJ8juonOvofqxV2CqZCBK3or-iEs60XIsZg3pqP28w
@host = http://localhost
@port = 8080

POST {{host}}:{{port}}/users/signup HTTP/1.1
content-type: application/json

{
  "username": "Dracoctix",
  "password": "password",
  "email": "dracoctix@outlook.fr"
}

#######
POST {{host}}:{{port}}/users/signin HTTP/1.1
content-type: application/json

{
  "email": "dracoctix@outlook.fr",
  "password": "password"
}

#######
GET {{host}}:{{port}}/users/get HTTP/1.1
  ?token={{token}}

# # #######
# GET {{host}}:{{port}}/admin/users/list HTTP/1.1
#   ?token={{token}}


# #######
# GET {{host}}:{{port}}/admin/users/list HTTP/1.1
#   ?token={{token}}
#   &options={"status": ["admin"]}