@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVjNWRlZGRiNTFkZjZhNTc5YzUxY2Q0NCIsInVzZXJuYW1lIjoiRHJhY29jdGl4IiwiYWRtaW4iOmZhbHNlLCJleHAiOjE1NDk2NTk2MjEwMjYsImlhdCI6MTU0OTY1OTYxMX0.qHJ8juonOvofqxV2CqZCBK3or-iEs60XIsZg3pqP28w
@host = http://localhost
@port = 8080

POST {{host}}:{{port}}/users/signup HTTP/1.1
content-type: application/json

{
  "username": "Dracoctix",
  "password": "password",
  "email": "dracoctix@outlook.fr"
}

#######
POST {{host}}:{{port}}/users/signin HTTP/1.1
content-type: application/json

{
  "email": "dracoctix@outlook.fr",
  "password": "password"
}

#######
GET {{host}}:{{port}}/users/get HTTP/1.1
  ?token={{token}}

# #######
GET {{host}}:{{port}}/admin/users/list HTTP/1.1
  ?token={{token}}

#######
POST {{host}}:{{port}}/admin/types/add HTTP/1.1
Content-Type: application/json

{
  "token": "{{token}}",
  "nom": "Anniversaire"
}

#####
GET {{host}}:{{port}}/types/get HTTP/1.1

# #######
# GET {{host}}:{{port}}/admin/users/list HTTP/1.1
#   ?token={{token}}
#   &options={"status": ["admin"]}
#####
POST {{host}}:{{port}}/admin/destinations/add HTTP/1.1
Content-Type: application/json

{
  "token": "{{token}}",
  "lieu": "Tours jumelles",
  "debut": "2001-09-11",
  "fin": "2001-09-12",
  "description": "Allahu Akbar !",
  "types": [
    "5c549b32d998462208e36b72"
  ]
}

#
#####
GET {{host}}:{{port}}/destinations/get HTTP/1.1

#####
POST {{host}}:{{port}}/events/add HTTP/1.1
Content-Type: application/json

{
  "token": "{{token}}",
  "date": "2019-03-05",
  "type": "5c549b32d998462208e36b72",
  "destination": "5c54b14639c92b0c64f76c62"
}